#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
  note "Next steps:"
  note "  1. Run 'pnpm dev' (or 'bun dev') to start the application."
  note "  2. Run 'pnpm check' and 'pnpm test' to verify health."
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "QuoteFlow Environment & Infrastructure Setup"

# ── Stage 1: OpenRouter AI Credentials ────────────────────────────────────
stage "OpenRouter AI setup"
say "We will configure your OpenRouter credentials for structured proposal generation."
open_url "https://openrouter.ai/keys"
step "Sign in to OpenRouter or create a free account."
step "Click 'Create Key', enter a key name (e.g., 'quoteflow-dev'), and click Create."
step "Copy the generated API key (starts with sk-or-v1-)."
ask_secret OPENROUTER_API_KEY "Paste your OpenRouter API key:"
while [[ -z "$OPENROUTER_API_KEY" ]]; do
  warn "OpenRouter API key cannot be empty to run proposal generation."
  ask_secret OPENROUTER_API_KEY "Paste your OpenRouter API key:"
done
write_env OPENROUTER_API_KEY "$OPENROUTER_API_KEY"

step "Select default AI model (press Enter to accept 'openai/gpt-4o-mini')."
ask OPENROUTER_MODEL "Model [default: openai/gpt-4o-mini]:"
[[ -z "$OPENROUTER_MODEL" ]] && OPENROUTER_MODEL="openai/gpt-4o-mini"
write_env OPENROUTER_MODEL "$OPENROUTER_MODEL"

# ── Stage 2: Database Connection String (NeonDB) ──────────────────────────
stage "NeonDB PostgreSQL database connection"
say "Configure your Neon Serverless PostgreSQL connection for proposals, versions, and audit logs."
open_url "https://console.neon.tech"
step "Sign in or create a project on Neon (https://neon.tech)."
step "On your Neon project dashboard, copy the pooled PostgreSQL connection string."
note "Format: postgresql://[user]:[password]@[endpoint].neon.tech/[dbname]?sslmode=require"
ask_secret DATABASE_URL "Paste your Neon DATABASE_URL:"
while [[ -z "$DATABASE_URL" ]]; do
  warn "DATABASE_URL is required to persist proposals and run drizzle commands."
  ask_secret DATABASE_URL "Paste your DATABASE_URL:"
done
write_env DATABASE_URL "$DATABASE_URL"

# ── Stage 3: Security & Session Secrets ───────────────────────────────────
stage "Session security & JWT secret"
say "QuoteFlow signs authentication sessions and cookies using JWT_SECRET."
existing_jwt=$(_existing "JWT_SECRET" || true)
if [[ -z "$existing_jwt" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    generated_jwt=$(openssl rand -hex 32)
  else
    generated_jwt=$(LC_ALL=C tr -dc 'a-zA-Z0-9' < /dev/urandom 2>/dev/null | head -c 64 || echo "random-secret-$(date +%s)")
  fi
  say "Generated a random 32-byte secure key."
  ask_secret JWT_SECRET "JWT_SECRET [Enter to use generated secret]:"
  [[ -z "$JWT_SECRET" ]] && JWT_SECRET="$generated_jwt"
else
  ask_secret JWT_SECRET "JWT_SECRET [Enter keeps current]:"
fi
write_env JWT_SECRET "$JWT_SECRET"

# ── Stage 4: Outbound Integration Webhook ─────────────────────────────────
stage "Outbound CRM webhook (optional)"
say "When a proposal is approved, QuoteFlow emits an outbound webhook."
say "In production this targets GoHighLevel (GHL). For testing, you can use Webhook.site."
open_url "https://webhook.site"
step "Copy your unique Webhook.site URL, or your GoHighLevel inbound webhook URL."
ask OUTBOUND_WEBHOOK_URL "OUTBOUND_WEBHOOK_URL [Enter to skip and use demo topic]:"
if [[ -n "$OUTBOUND_WEBHOOK_URL" ]]; then
  write_env OUTBOUND_WEBHOOK_URL "$OUTBOUND_WEBHOOK_URL"
else
  note "Skipped. QuoteFlow will use the built-in demo ntfy topic."
fi

# ── Stage 5: Database Push & Migration ────────────────────────────────────
stage "Database push & initialization"
say "We can now push the database schema to your database to create all tables."
step "This executes 'pnpm db:push' (or 'bun run db:push') using the DATABASE_URL."
if confirm "Run database push now?"; then
  printf '\n'
  if command -v pnpm >/dev/null 2>&1; then
    pnpm db:push || warn "pnpm db:push reported an issue. Check connection string & network."
  elif command -v bun >/dev/null 2>&1; then
    bun run db:push || warn "bun run db:push reported an issue. Check connection string & network."
  elif command -v npm >/dev/null 2>&1; then
    npm run db:push || warn "npm run db:push reported an issue. Check connection string & network."
  else
    warn "Neither pnpm, bun, nor npm found in PATH. Run db:push manually."
  fi
  pause "Press Enter to continue after reviewing output."
else
  note "Skipped database push. You can run 'pnpm db:push' manually later."
fi

finish
