#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
  note "Deployment runner:"
  note "  You can run 'bash scripts/deploy.sh' anytime to build & deploy to Vercel."
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE="${ENV_FILE:-.env.production}"
TOTAL_STAGES=8

banner "QuoteFlow Vercel Production Deployment Setup"

# ── Stage 1: Codebase & Vercel Configuration Verification ─────────────────
stage "Codebase & Vercel configuration verification"
say "Verifying that vercel.json and api/index.ts are configured for serverless execution."
if [[ ! -f "vercel.json" ]]; then
  warn "vercel.json missing! Creating default routing config..."
  printf '{\n  "version": 2,\n  "buildCommand": "bun run build",\n  "outputDirectory": "dist/public",\n  "rewrites": [\n    { "source": "/api/(.*)", "destination": "/api" },\n    { "source": "/(.*)", "destination": "/index.html" }\n  ]\n}\n' > vercel.json
fi

if [[ ! -f "api/index.ts" ]]; then
  warn "api/index.ts missing! Creating serverless function adapter..."
  mkdir -p api
  printf 'import { createExpressApp } from "../server/_core/app";\n\nconst app = createExpressApp();\nexport default app;\n' > api/index.ts
fi

step "Checking TypeScript and project build before remote deployment..."
if command -v bun >/dev/null 2>&1; then
  bun run check
elif command -v pnpm >/dev/null 2>&1; then
  pnpm check
fi
say "Code checks passed."
pause "Press Enter to proceed to production database setup."

# ── Stage 2: NeonDB Production Database Connection ────────────────────────
stage "NeonDB PostgreSQL production database"
say "QuoteFlow requires a serverless PostgreSQL database to persist proposals and audit logs."
open_url "https://console.neon.tech"
step "Sign in or select your Neon project."
step "Select your production database branch (or the main branch) and copy the pooled connection string."
note "Format: postgresql://[user]:[password]@[endpoint].neon.tech/[dbname]?sslmode=require"
ask_secret DATABASE_URL "Paste your production Neon DATABASE_URL:"
while [[ -z "$DATABASE_URL" ]]; do
  warn "DATABASE_URL is required for production operations."
  ask_secret DATABASE_URL "Paste your production Neon DATABASE_URL:"
done
write_env DATABASE_URL "$DATABASE_URL"

step "Push database schema migrations to this database?"
if confirm "Run schema push now?"; then
  if command -v bun >/dev/null 2>&1; then
    DATABASE_URL="$DATABASE_URL" bun run db:push || warn "Database push encountered an error."
  elif command -v pnpm >/dev/null 2>&1; then
    DATABASE_URL="$DATABASE_URL" pnpm db:push || warn "Database push encountered an error."
  fi
  pause "Review database output and press Enter to continue."
else
  note "Skipping schema push. Remember to run 'bun run db:push' before using proposals."
fi

# ── Stage 3: OpenRouter AI Credentials ────────────────────────────────────
stage "OpenRouter AI setup"
say "QuoteFlow uses OpenRouter to generate structured landscaping proposals from notes."
open_url "https://openrouter.ai/keys"
step "On OpenRouter API Keys page, create or copy your production API key."
ask_secret OPENROUTER_API_KEY "Paste your OpenRouter API key (sk-or-v1-...):"
while [[ -z "$OPENROUTER_API_KEY" ]]; do
  warn "OPENROUTER_API_KEY cannot be empty."
  ask_secret OPENROUTER_API_KEY "Paste your OpenRouter API key:"
done
write_env OPENROUTER_API_KEY "$OPENROUTER_API_KEY"

step "Specify production AI model (press Enter for default 'openai/gpt-4o-mini')."
ask OPENROUTER_MODEL "Model [default: openai/gpt-4o-mini]:"
[[ -z "$OPENROUTER_MODEL" ]] && OPENROUTER_MODEL="openai/gpt-4o-mini"
write_env OPENROUTER_MODEL "$OPENROUTER_MODEL"

# ── Stage 4: Session Security & JWT Secret ─────────────────────────────────
stage "Session security & JWT secret"
say "Configure the cryptographic secret used to sign session cookies."
existing_jwt=$(_existing "JWT_SECRET" || true)
if [[ -z "$existing_jwt" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    generated_jwt=$(openssl rand -hex 32)
  else
    generated_jwt=$(LC_ALL=C tr -dc 'a-zA-Z0-9' < /dev/urandom 2>/dev/null | head -c 64 || echo "random-secret-$(date +%s)")
  fi
  say "Generated random 32-byte production secret."
  ask_secret JWT_SECRET "JWT_SECRET [Enter accepts generated secret]:"
  [[ -z "$JWT_SECRET" ]] && JWT_SECRET="$generated_jwt"
else
  ask_secret JWT_SECRET "JWT_SECRET [Enter keeps current]:"
fi
write_env JWT_SECRET "$JWT_SECRET"

# ── Stage 5: Vercel Project Import & Domain Setup ─────────────────────────
stage "Vercel project setup & production domain"
say "We will link QuoteFlow to your Vercel account and establish its production domain."
open_url "https://vercel.com/new"
step "In Vercel, click 'Import' next to the 'denniarems/greenscape-quoteflow' repository."
step "Choose your project name (e.g. 'greenscape-quoteflow')."
step "Note the assigned production domain (e.g. 'https://greenscape-quoteflow.vercel.app')."
ask APP_URL "Enter production domain / APP_URL (e.g. https://greenscape-quoteflow.vercel.app):"
while [[ -z "$APP_URL" ]]; do
  warn "APP_URL is required to properly configure OAuth redirects."
  ask APP_URL "Enter production domain / APP_URL:"
done
# Ensure leading https:// if missing
[[ "$APP_URL" =~ ^https?:// ]] || APP_URL="https://$APP_URL"
# Remove trailing slash
APP_URL="${APP_URL%/}"
write_env APP_URL "$APP_URL"

# ── Stage 6: GitHub OAuth Configuration ───────────────────────────────────
stage "GitHub OAuth application for production domain"
say "Configure GitHub OAuth to authenticate team members against the live domain."
open_url "https://github.com/settings/applications/new"
step "Register a new OAuth Application (or edit an existing one) with:"
note "  • Application name: QuoteFlow (Production)"
note "  • Homepage URL: $APP_URL"
note "  • Authorization callback URL: $APP_URL/api/oauth/callback"
step "Click 'Register application' and copy the Client ID."
ask GITHUB_CLIENT_ID "GitHub Client ID [Enter to skip authentication]:"

if [[ -n "$GITHUB_CLIENT_ID" ]]; then
  write_env GITHUB_CLIENT_ID "$GITHUB_CLIENT_ID"
  write_env VITE_GITHUB_CLIENT_ID "$GITHUB_CLIENT_ID"

  step "Click 'Generate a new client secret' and copy it."
  ask_secret GITHUB_CLIENT_SECRET "GitHub Client Secret:"
  while [[ -z "$GITHUB_CLIENT_SECRET" ]]; do
    warn "Client Secret is required when Client ID is configured."
    ask_secret GITHUB_CLIENT_SECRET "GitHub Client Secret:"
  done
  write_env GITHUB_CLIENT_SECRET "$GITHUB_CLIENT_SECRET"

  ask OWNER_OPEN_ID "Owner GitHub Username for admin access [default: admin]:"
  [[ -z "$OWNER_OPEN_ID" ]] && OWNER_OPEN_ID="admin"
  write_env OWNER_OPEN_ID "$OWNER_OPEN_ID"
else
  note "Skipped OAuth configuration. Assessment evaluation mode remains open."
fi

# ── Stage 7: Outbound CRM Webhook (Optional) ──────────────────────────────
stage "Outbound CRM webhook (optional)"
say "When a proposal is approved, QuoteFlow dispatches an outbound event payload."
say "In production this connects to GoHighLevel (GHL). For webhook inspection, use Webhook.site."
open_url "https://webhook.site"
step "Copy your GoHighLevel inbound webhook URL or Webhook.site target."
ask OUTBOUND_WEBHOOK_URL "OUTBOUND_WEBHOOK_URL [Enter to skip and use demo ntfy topic]:"
if [[ -n "$OUTBOUND_WEBHOOK_URL" ]]; then
  write_env OUTBOUND_WEBHOOK_URL "$OUTBOUND_WEBHOOK_URL"
else
  note "Skipped. Defaulting to built-in live demo notification channel."
fi

# ── Stage 8: Vercel Environment Variables & Deploy Handoff ────────────────
stage "Provision Vercel environment variables & deploy handoff"
say "The captured configuration has been stored locally in $ENV_FILE."
say "We must ensure these environment variables are populated in your Vercel Project."
open_url "https://vercel.com/dashboard"
step "In Vercel dashboard: Project → Settings → Environment Variables."
step "Add each of the following variables:"
note "  • DATABASE_URL"
note "  • OPENROUTER_API_KEY"
note "  • OPENROUTER_MODEL"
note "  • JWT_SECRET"
note "  • APP_URL"
[[ -n "${GITHUB_CLIENT_ID:-}" ]] && note "  • GITHUB_CLIENT_ID and VITE_GITHUB_CLIENT_ID"
[[ -n "${GITHUB_CLIENT_SECRET:-}" ]] && note "  • GITHUB_CLIENT_SECRET"
[[ -n "${OUTBOUND_WEBHOOK_URL:-}" ]] && note "  • OUTBOUND_WEBHOOK_URL"

printf '\n'
if command -v vercel >/dev/null 2>&1 || npx --yes vercel --version >/dev/null 2>&1; then
  if confirm "Would you like to run the separate deploy script (bash scripts/deploy.sh) now?"; then
    printf '\n'
    bash scripts/deploy.sh || warn "Deploy script reported an error. You can run it manually anytime: bash scripts/deploy.sh"
    pause "Press Enter after reviewing deployment output."
  fi
else
  note "Vercel CLI not detected. You can push commits to GitHub to trigger Vercel deployment,"
  note "or run the separate deploy script anytime: bash scripts/deploy.sh"
  pause "Press Enter to finalize setup."
fi

finish
