/* @generated by esbuild - DO NOT EDIT DIRECTLY */
var __defProp = Object.defineProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

// server/_core/app.ts
import "dotenv/config";
import express from "express";
import { createExpressMiddleware } from "@trpc/server/adapters/express";

// server/_core/env.ts
var ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  openRouterApiKey: process.env.OPENROUTER_API_KEY ?? process.env.OPENAI_API_KEY ?? "",
  openRouterModel: process.env.OPENROUTER_MODEL ?? process.env.AI_MODEL ?? "",
  openRouterBaseUrl: process.env.OPENROUTER_BASE_URL ?? "https://openrouter.ai/api/v1",
  appUrl: process.env.APP_URL ?? "http://localhost:3000"
};

// server/_core/storageProxy.ts
function registerStorageProxy(app2) {
  app2.get("/storage/*", async (req, res) => {
    const key = req.params[0];
    if (!key) {
      res.status(400).send("Missing storage key");
      return;
    }
    if (!ENV.forgeApiUrl || !ENV.forgeApiKey) {
      res.status(500).send("Storage proxy not configured");
      return;
    }
    try {
      const forgeUrl = new URL(
        "v1/storage/presign/get",
        ENV.forgeApiUrl.replace(/\/+$/, "") + "/"
      );
      forgeUrl.searchParams.set("path", key);
      const forgeResp = await fetch(forgeUrl, {
        headers: { Authorization: `Bearer ${ENV.forgeApiKey}` }
      });
      if (!forgeResp.ok) {
        const body = await forgeResp.text().catch(() => "");
        console.error(
          `[StorageProxy] forge error: ${forgeResp.status} ${body}`
        );
        res.status(502).send("Storage backend error");
        return;
      }
      const { url } = await forgeResp.json();
      if (!url) {
        res.status(502).send("Empty signed URL from backend");
        return;
      }
      res.set("Cache-Control", "no-store");
      res.redirect(307, url);
    } catch (err) {
      console.error("[StorageProxy] failed:", err);
      res.status(502).send("Storage proxy error");
    }
  });
}

// server/routers.ts
import { z as z3 } from "zod";

// shared/const.ts
var COOKIE_NAME = "app_session_id";
var ONE_YEAR_MS = 1e3 * 60 * 60 * 24 * 365;
var UNAUTHED_ERR_MSG = "Please login (10001)";
var NOT_ADMIN_ERR_MSG = "You do not have required permission (10002)";

// server/_core/cookies.ts
function isSecureRequest(req) {
  if (req.protocol === "https") return true;
  const forwardedProto = req.headers["x-forwarded-proto"];
  if (!forwardedProto) return false;
  const protoList = Array.isArray(forwardedProto) ? forwardedProto : forwardedProto.split(",");
  return protoList.some((proto) => proto.trim().toLowerCase() === "https");
}
function getSessionCookieOptions(req) {
  return {
    httpOnly: true,
    path: "/",
    sameSite: "none",
    secure: isSecureRequest(req)
  };
}

// server/_core/systemRouter.ts
import { z } from "zod";

// server/_core/notification.ts
import { TRPCError } from "@trpc/server";
var TITLE_MAX_LENGTH = 1200;
var CONTENT_MAX_LENGTH = 2e4;
var trimValue = (value) => value.trim();
var isNonEmptyString = (value) => typeof value === "string" && value.trim().length > 0;
var buildEndpointUrl = (baseUrl) => {
  const normalizedBase = baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`;
  return new URL(
    "webdevtoken.v1.WebDevService/SendNotification",
    normalizedBase
  ).toString();
};
var validatePayload = (input) => {
  if (!isNonEmptyString(input.title)) {
    throw new TRPCError({
      code: "BAD_REQUEST",
      message: "Notification title is required."
    });
  }
  if (!isNonEmptyString(input.content)) {
    throw new TRPCError({
      code: "BAD_REQUEST",
      message: "Notification content is required."
    });
  }
  const title = trimValue(input.title);
  const content = trimValue(input.content);
  if (title.length > TITLE_MAX_LENGTH) {
    throw new TRPCError({
      code: "BAD_REQUEST",
      message: `Notification title must be at most ${TITLE_MAX_LENGTH} characters.`
    });
  }
  if (content.length > CONTENT_MAX_LENGTH) {
    throw new TRPCError({
      code: "BAD_REQUEST",
      message: `Notification content must be at most ${CONTENT_MAX_LENGTH} characters.`
    });
  }
  return { title, content };
};
async function notifyOwner(payload) {
  const { title, content } = validatePayload(payload);
  if (!ENV.forgeApiUrl) {
    throw new TRPCError({
      code: "INTERNAL_SERVER_ERROR",
      message: "Notification service URL is not configured."
    });
  }
  if (!ENV.forgeApiKey) {
    throw new TRPCError({
      code: "INTERNAL_SERVER_ERROR",
      message: "Notification service API key is not configured."
    });
  }
  const endpoint = buildEndpointUrl(ENV.forgeApiUrl);
  try {
    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        accept: "application/json",
        authorization: `Bearer ${ENV.forgeApiKey}`,
        "content-type": "application/json",
        "connect-protocol-version": "1"
      },
      body: JSON.stringify({ title, content })
    });
    if (!response.ok) {
      const detail = await response.text().catch(() => "");
      console.warn(
        `[Notification] Failed to notify owner (${response.status} ${response.statusText})${detail ? `: ${detail}` : ""}`
      );
      return false;
    }
    return true;
  } catch (error) {
    console.warn("[Notification] Error calling notification service:", error);
    return false;
  }
}

// server/_core/trpc.ts
import { initTRPC, TRPCError as TRPCError2 } from "@trpc/server";
import superjson from "superjson";
var t = initTRPC.context().create({
  transformer: superjson
});
var router = t.router;
var publicProcedure = t.procedure;
var requireUser = t.middleware(async (opts) => {
  const { ctx, next } = opts;
  if (!ctx.user) {
    throw new TRPCError2({ code: "UNAUTHORIZED", message: UNAUTHED_ERR_MSG });
  }
  return next({
    ctx: {
      ...ctx,
      user: ctx.user
    }
  });
});
var protectedProcedure = t.procedure.use(requireUser);
var adminProcedure = t.procedure.use(
  t.middleware(async (opts) => {
    const { ctx, next } = opts;
    if (!ctx.user || ctx.user.role !== "admin") {
      throw new TRPCError2({ code: "FORBIDDEN", message: NOT_ADMIN_ERR_MSG });
    }
    return next({
      ctx: {
        ...ctx,
        user: ctx.user
      }
    });
  })
);

// server/_core/systemRouter.ts
var systemRouter = router({
  health: publicProcedure.input(
    z.object({
      timestamp: z.number().min(0, "timestamp cannot be negative")
    })
  ).query(() => ({
    ok: true
  })),
  notifyOwner: adminProcedure.input(
    z.object({
      title: z.string().min(1, "title is required"),
      content: z.string().min(1, "content is required")
    })
  ).mutation(async ({ input }) => {
    const delivered = await notifyOwner(input);
    return {
      success: delivered
    };
  })
});

// server/db.ts
import { desc, eq } from "drizzle-orm";
import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";

// drizzle/schema.ts
var schema_exports = {};
__export(schema_exports, {
  integrationEvents: () => integrationEvents,
  integrationStatusEnum: () => integrationStatusEnum,
  proposalStatusEnum: () => proposalStatusEnum,
  proposals: () => proposals,
  userRoleEnum: () => userRoleEnum,
  users: () => users
});
import {
  integer,
  pgEnum,
  pgTable,
  serial,
  text,
  timestamp,
  varchar
} from "drizzle-orm/pg-core";
var userRoleEnum = pgEnum("role", ["user", "admin"]);
var proposalStatusEnum = pgEnum("proposal_status", [
  "draft",
  "approved"
]);
var integrationStatusEnum = pgEnum("integration_status", [
  "sent",
  "failed"
]);
var users = pgTable("users", {
  id: serial("id").primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: userRoleEnum("role").default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => /* @__PURE__ */ new Date()).notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull()
});
var proposals = pgTable("proposals", {
  id: serial("id").primaryKey(),
  customerName: varchar("customerName", { length: 160 }).notNull(),
  customerEmail: varchar("customerEmail", { length: 320 }),
  customerPhone: varchar("customerPhone", { length: 40 }),
  projectAddress: varchar("projectAddress", { length: 320 }).notNull(),
  projectType: varchar("projectType", { length: 160 }).notNull(),
  desiredStartDate: varchar("desiredStartDate", { length: 80 }),
  budgetRange: varchar("budgetRange", { length: 80 }),
  siteNotes: text("siteNotes").notNull(),
  status: proposalStatusEnum("status").default("draft").notNull(),
  projectSummary: text("projectSummary").notNull(),
  lineItemsJson: text("lineItemsJson").notNull(),
  assumptionsJson: text("assumptionsJson").notNull(),
  exclusionsJson: text("exclusionsJson").notNull(),
  unansweredQuestionsJson: text("unansweredQuestionsJson").notNull(),
  riskFlagsJson: text("riskFlagsJson").notNull(),
  customerMessage: text("customerMessage").notNull(),
  totalCents: integer("totalCents").notNull(),
  aiModel: varchar("aiModel", { length: 80 }).notNull(),
  promptTokens: integer("promptTokens"),
  completionTokens: integer("completionTokens"),
  version: integer("version").default(1).notNull(),
  approvedAt: timestamp("approvedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => /* @__PURE__ */ new Date()).notNull()
});
var integrationEvents = pgTable("integration_events", {
  id: serial("id").primaryKey(),
  proposalId: integer("proposalId").notNull(),
  destination: varchar("destination", { length: 255 }).notNull(),
  status: integrationStatusEnum("status").notNull(),
  httpStatus: integer("httpStatus"),
  responseSnippet: text("responseSnippet"),
  createdAt: timestamp("createdAt").defaultNow().notNull()
});

// server/db.ts
var _db = null;
async function getDb() {
  if (!_db && process.env.DATABASE_URL) {
    try {
      const sql = neon(process.env.DATABASE_URL);
      _db = drizzle({ client: sql, schema: schema_exports });
    } catch (error) {
      console.warn("[Database] Failed to connect:", error);
      _db = null;
    }
  }
  return _db;
}
async function requireDb() {
  const db = await getDb();
  if (!db) throw new Error("Database is not configured");
  return db;
}
async function listProposalRows() {
  const db = await requireDb();
  return db.select().from(proposals).orderBy(desc(proposals.updatedAt));
}
async function getProposalRow(id) {
  const db = await requireDb();
  const result = await db.select().from(proposals).where(eq(proposals.id, id)).limit(1);
  return result[0];
}
async function createProposalRow(values) {
  const db = await requireDb();
  const result = await db.insert(proposals).values(values).returning();
  return result[0];
}
async function updateProposalRow(id, values) {
  const db = await requireDb();
  const result = await db.update(proposals).set(values).where(eq(proposals.id, id)).returning();
  return result[0];
}
async function createIntegrationEvent(values) {
  const db = await requireDb();
  await db.insert(integrationEvents).values(values);
}
async function listIntegrationEvents(proposalId) {
  const db = await requireDb();
  return db.select().from(integrationEvents).where(eq(integrationEvents.proposalId, proposalId)).orderBy(desc(integrationEvents.createdAt));
}

// server/proposal-service.ts
import { TRPCError as TRPCError3 } from "@trpc/server";
import { z as z2 } from "zod";

// server/_core/llm.ts
var ensureArray = (value) => Array.isArray(value) ? value : [value];
var normalizeContentPart = (part) => {
  if (typeof part === "string") {
    return { type: "text", text: part };
  }
  if (part.type === "text") {
    return part;
  }
  if (part.type === "image_url") {
    return part;
  }
  if (part.type === "file_url") {
    return part;
  }
  throw new Error("Unsupported message content part");
};
var normalizeMessage = (message) => {
  const { role, name, tool_call_id } = message;
  if (role === "tool" || role === "function") {
    const content = ensureArray(message.content).map((part) => typeof part === "string" ? part : JSON.stringify(part)).join("\n");
    return {
      role,
      name,
      tool_call_id,
      content
    };
  }
  const contentParts = ensureArray(message.content).map(normalizeContentPart);
  if (contentParts.length === 1 && contentParts[0].type === "text") {
    return {
      role,
      name,
      content: contentParts[0].text
    };
  }
  return {
    role,
    name,
    content: contentParts
  };
};
var normalizeToolChoice = (toolChoice, tools) => {
  if (!toolChoice) return void 0;
  if (toolChoice === "none" || toolChoice === "auto") {
    return toolChoice;
  }
  if (toolChoice === "required") {
    if (!tools || tools.length === 0) {
      throw new Error(
        "tool_choice 'required' was provided but no tools were configured"
      );
    }
    if (tools.length > 1) {
      throw new Error(
        "tool_choice 'required' needs a single tool or specify the tool name explicitly"
      );
    }
    return {
      type: "function",
      function: { name: tools[0].function.name }
    };
  }
  if ("name" in toolChoice) {
    return {
      type: "function",
      function: { name: toolChoice.name }
    };
  }
  return toolChoice;
};
var resolveApiKey = () => process.env.OPENROUTER_API_KEY || ENV.openRouterApiKey || ENV.forgeApiKey || process.env.OPENAI_API_KEY || "";
var resolveApiUrl = () => {
  if (ENV.forgeApiUrl && ENV.forgeApiUrl.trim().length > 0) {
    return `${ENV.forgeApiUrl.replace(/\/$/, "")}/v1/chat/completions`;
  }
  const base = process.env.OPENROUTER_BASE_URL || ENV.openRouterBaseUrl || "https://openrouter.ai/api/v1";
  return `${base.replace(/\/$/, "")}/chat/completions`;
};
var assertApiKey = () => {
  if (!resolveApiKey()) {
    throw new Error("OPENROUTER_API_KEY is not configured");
  }
};
var normalizeResponseFormat = ({
  responseFormat,
  response_format,
  outputSchema,
  output_schema
}) => {
  const explicitFormat = responseFormat || response_format;
  if (explicitFormat) {
    if (explicitFormat.type === "json_schema" && !explicitFormat.json_schema?.schema) {
      throw new Error(
        "responseFormat json_schema requires a defined schema object"
      );
    }
    return explicitFormat;
  }
  const schema = outputSchema || output_schema;
  if (!schema) return void 0;
  if (!schema.name || !schema.schema) {
    throw new Error("outputSchema requires both name and schema");
  }
  return {
    type: "json_schema",
    json_schema: {
      name: schema.name,
      schema: schema.schema,
      ...typeof schema.strict === "boolean" ? { strict: schema.strict } : {}
    }
  };
};
var RETRY_MAX_RETRIES = 4;
var RETRY_BASE_DELAY_MS = 500;
var RETRY_MAX_DELAY_MS = 3e4;
var sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
var parseRetryAfter = (value) => {
  if (!value) return void 0;
  const seconds = Number(value);
  if (Number.isFinite(seconds)) return Math.max(0, seconds * 1e3);
  const at = Date.parse(value);
  return Number.isNaN(at) ? void 0 : Math.max(0, at - Date.now());
};
var computeBackoffDelay = (attempt, retryAfterMs) => {
  const cap = Math.min(RETRY_BASE_DELAY_MS * 2 ** attempt, RETRY_MAX_DELAY_MS);
  const jittered = cap / 2 + Math.random() * (cap / 2);
  return Math.min(Math.max(jittered, retryAfterMs ?? 0), RETRY_MAX_DELAY_MS);
};
var fetchWithBackoff = async (url, init) => {
  let lastError;
  for (let attempt = 0; attempt <= RETRY_MAX_RETRIES; attempt++) {
    try {
      const response = await fetch(url, init);
      if (response.ok || attempt === RETRY_MAX_RETRIES) {
        return response;
      }
      const retryAfterMs = parseRetryAfter(response.headers.get("retry-after"));
      try {
        await response.body?.cancel();
      } catch {
      }
      console.warn(
        `LLM request retry ${attempt + 1}/${RETRY_MAX_RETRIES} after status ${response.status}`
      );
      await sleep(computeBackoffDelay(attempt, retryAfterMs));
    } catch (error) {
      lastError = error;
      if (attempt === RETRY_MAX_RETRIES) throw error;
      console.warn(
        `LLM request retry ${attempt + 1}/${RETRY_MAX_RETRIES} after network error`
      );
      await sleep(computeBackoffDelay(attempt));
    }
  }
  throw lastError instanceof Error ? lastError : new Error("LLM request failed after exhausting retries");
};
async function invokeLLM(params) {
  assertApiKey();
  const {
    messages,
    tools,
    toolChoice,
    tool_choice,
    outputSchema,
    output_schema,
    responseFormat,
    response_format,
    model,
    thinking,
    reasoning,
    maxTokens,
    max_tokens
  } = params;
  const apiKey = resolveApiKey();
  const isForge = Boolean(
    ENV.forgeApiUrl && ENV.forgeApiUrl.trim().length > 0
  );
  const payload = {
    messages: messages.map(normalizeMessage)
  };
  payload.model = model || process.env.OPENROUTER_MODEL || ENV.openRouterModel || (isForge ? "gpt-5-mini" : "openai/gpt-4o-mini");
  if (tools && tools.length > 0) {
    payload.tools = tools;
  }
  const normalizedToolChoice = normalizeToolChoice(
    toolChoice || tool_choice,
    tools
  );
  if (normalizedToolChoice) {
    payload.tool_choice = normalizedToolChoice;
  }
  const resolvedMaxTokens = max_tokens ?? maxTokens;
  if (typeof resolvedMaxTokens === "number") {
    payload.max_tokens = resolvedMaxTokens;
  }
  if (thinking) {
    payload.thinking = thinking;
  }
  if (reasoning && isForge) {
    payload.reasoning = reasoning;
  }
  const normalizedResponseFormat = normalizeResponseFormat({
    responseFormat,
    response_format,
    outputSchema,
    output_schema
  });
  if (normalizedResponseFormat) {
    payload.response_format = normalizedResponseFormat;
  }
  const headers = {
    "content-type": "application/json",
    authorization: `Bearer ${apiKey}`
  };
  if (!isForge) {
    headers["HTTP-Referer"] = process.env.APP_URL || ENV.appUrl || "http://localhost:3000";
    headers["X-Title"] = "Greenscape QuoteFlow";
  }
  const response = await fetchWithBackoff(resolveApiUrl(), {
    method: "POST",
    headers,
    body: JSON.stringify(payload)
  });
  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(
      `LLM invoke failed: ${response.status} ${response.statusText} \u2013 ${errorText}`
    );
  }
  return await response.json();
}

// server/proposal-service.ts
function getProposalModel() {
  return process.env.OPENROUTER_MODEL || process.env.AI_MODEL || (process.env.BUILT_IN_FORGE_API_URL ? "gpt-5-mini" : "openai/gpt-4o-mini");
}
var DEMO_WEBHOOK_URL = "https://ntfy.sh/greenscape-quoteflow-assessment";
var lineItemSchema = z2.object({
  category: z2.string().min(1).max(120),
  description: z2.string().min(1).max(500),
  quantity: z2.number().positive().max(1e5),
  unit: z2.string().min(1).max(40),
  unitPriceCents: z2.number().int().nonnegative().max(1e7),
  sourceNote: z2.string().nullish().transform((val) => val?.trim() ? val.trim() : "Site walk scope note")
});
var riskFlagSchema = z2.object({
  severity: z2.enum(["low", "medium", "high"]),
  message: z2.string().min(1).max(500)
});
var generatedProposalSchema = z2.object({
  projectSummary: z2.string().nullish().transform(
    (val) => val?.trim() ? val.trim() : "Custom landscape and hardscape design and installation proposal."
  ),
  lineItems: z2.array(lineItemSchema).min(1).max(50),
  assumptions: z2.array(z2.string()).transform((items) => items.map((s) => s.trim()).filter(Boolean)).default([]),
  exclusions: z2.array(z2.string()).transform((items) => items.map((s) => s.trim()).filter(Boolean)).default([]),
  unansweredQuestions: z2.array(z2.string()).transform((items) => items.map((s) => s.trim()).filter(Boolean)).default([]),
  riskFlags: z2.array(riskFlagSchema).default([]),
  customerMessage: z2.string().nullish().transform(
    (val) => val?.trim() ? val.trim() : "Thank you for the opportunity to quote your landscape project. Please review our detailed estimate and line-item breakdown below."
  )
});
var generatedSchema = {
  type: "object",
  properties: {
    projectSummary: {
      type: "string",
      description: "Comprehensive summary of the project scope and site design."
    },
    lineItems: {
      type: "array",
      items: {
        type: "object",
        properties: {
          category: { type: "string" },
          description: { type: "string" },
          quantity: { type: "number" },
          unit: { type: "string" },
          unitPriceCents: { type: "integer" },
          sourceNote: { type: "string" }
        },
        required: [
          "category",
          "description",
          "quantity",
          "unit",
          "unitPriceCents",
          "sourceNote"
        ],
        additionalProperties: false
      }
    },
    assumptions: { type: "array", items: { type: "string" } },
    exclusions: { type: "array", items: { type: "string" } },
    unansweredQuestions: { type: "array", items: { type: "string" } },
    riskFlags: {
      type: "array",
      items: {
        type: "object",
        properties: {
          severity: { type: "string", enum: ["low", "medium", "high"] },
          message: { type: "string" }
        },
        required: ["severity", "message"],
        additionalProperties: false
      }
    },
    customerMessage: {
      type: "string",
      description: "A warm, professional 2-4 sentence customer-facing cover note introducing the proposal and next steps."
    }
  },
  required: [
    "projectSummary",
    "lineItems",
    "assumptions",
    "exclusions",
    "unansweredQuestions",
    "riskFlags",
    "customerMessage"
  ],
  additionalProperties: false
};
var proposalInputSchema = z2.object({
  customerName: z2.string().min(2).max(160),
  customerEmail: z2.string().email().optional().or(z2.literal("")),
  customerPhone: z2.string().max(40).optional(),
  projectAddress: z2.string().min(8).max(320),
  projectType: z2.string().min(3).max(160),
  desiredStartDate: z2.string().max(80).optional(),
  budgetRange: z2.string().max(80).optional(),
  siteNotes: z2.string().min(80).max(12e3)
});
var editableSchema = z2.object({
  projectSummary: z2.string().min(1).max(4e3),
  lineItems: z2.array(lineItemSchema).min(1).max(50),
  assumptions: z2.array(z2.string().max(500)).max(50),
  exclusions: z2.array(z2.string().max(500)).max(50),
  unansweredQuestions: z2.array(z2.string().max(500)).max(50),
  riskFlags: z2.array(riskFlagSchema).max(50),
  customerMessage: z2.string().max(4e3)
});
function calculateTotal(lineItems) {
  return lineItems.reduce(
    (sum, item) => sum + Math.round(item.quantity * item.unitPriceCents),
    0
  );
}
function evaluateGuardrails(lineItems, unansweredQuestions, modelFlags = []) {
  const flags = modelFlags.map((flag) => {
    const warrantsBlock = /(safety|hazard|structural failure|gas line|electrical hazard|contradict)/i.test(
      flag.message
    );
    return flag.severity === "high" && !warrantsBlock ? { ...flag, severity: "medium" } : flag;
  });
  const total = calculateTotal(lineItems);
  if (lineItems.length === 0)
    flags.push({
      severity: "high",
      message: "No billable scope items were generated."
    });
  if (total < 8e5)
    flags.push({
      severity: "high",
      message: "Draft total is below Greenscape Pro's typical $8,000 project floor."
    });
  if (total > 12e6)
    flags.push({
      severity: "medium",
      message: "Draft total exceeds the historical $120,000 project range; verify pricing."
    });
  if (unansweredQuestions.length > 0)
    flags.push({
      severity: "medium",
      message: `${unansweredQuestions.length} open question${unansweredQuestions.length === 1 ? "" : "s"} should be reviewed before approval.`
    });
  lineItems.forEach((item, index) => {
    if (!Number.isFinite(item.quantity) || !Number.isInteger(item.unitPriceCents)) {
      flags.push({
        severity: "high",
        message: `Line ${index + 1} contains invalid numeric pricing data.`
      });
    }
  });
  const deduped = new Map(
    flags.map((flag) => [`${flag.severity}:${flag.message}`, flag])
  );
  return Array.from(deduped.values());
}
function safeParseArray(value) {
  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}
function hydrateProposal(row) {
  return {
    id: row.id,
    customerName: row.customerName,
    customerEmail: row.customerEmail,
    customerPhone: row.customerPhone,
    projectAddress: row.projectAddress,
    projectType: row.projectType,
    desiredStartDate: row.desiredStartDate,
    budgetRange: row.budgetRange,
    siteNotes: row.siteNotes,
    status: row.status,
    projectSummary: row.projectSummary,
    lineItems: safeParseArray(row.lineItemsJson),
    assumptions: safeParseArray(row.assumptionsJson),
    exclusions: safeParseArray(row.exclusionsJson),
    unansweredQuestions: safeParseArray(row.unansweredQuestionsJson),
    riskFlags: safeParseArray(row.riskFlagsJson),
    customerMessage: row.customerMessage,
    totalCents: row.totalCents,
    aiModel: row.aiModel,
    promptTokens: row.promptTokens,
    completionTokens: row.completionTokens,
    version: row.version,
    approvedAt: row.approvedAt,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt
  };
}
async function requestStructuredProposal(input) {
  const system = `You are the proposal operations copilot for Greenscape Pro, a premium Phoenix landscape and hardscape design-build firm. Convert site-walk notes into a precise proposal draft. Never claim a permit, HOA approval, engineering result, or measurement that is not in the notes. Use realistic Phoenix premium-contractor allowances when exact catalog pricing is unavailable and disclose each allowance in assumptions. Use high severity only for a genuine safety, legal, or internally contradictory issue; ordinary missing details belong in unansweredQuestions. Write a warm, professional 2-4 sentence customer-facing cover note in customerMessage. Return only schema-valid JSON with these exact keys: "projectSummary" (string), "lineItems" (array of objects with category, description, quantity, unit, unitPriceCents, sourceNote), "assumptions" (array of strings), "exclusions" (array of strings), "unansweredQuestions" (array of strings), "riskFlags" (array of objects with severity and message), "customerMessage" (string).`;
  const pricingReference = `Representative assessment catalog (replace with the client's 200+ line catalog in production): demolition $4-$9/sq ft; premium pavers installed $22-$32/sq ft; concrete footing allowance $850/each; cedar/alumawood pergola $90-$150/sq ft; artificial turf $14-$20/sq ft; drip irrigation zone $1,400-$2,400; outdoor kitchen base $900-$1,500/linear ft excluding appliances; low-voltage lighting $350-$600/fixture; mobilization/design $1,500-$3,500. Price in integer cents.`;
  const user = `${pricingReference}

Customer: ${input.customerName}
Address: ${input.projectAddress}
Project type: ${input.projectType}
Desired start: ${input.desiredStartDate || "Not stated"}
Budget: ${input.budgetRange || "Not stated"}

Site-walk notes:
${input.siteNotes}`;
  const model = getProposalModel();
  const request = {
    model,
    messages: [
      { role: "system", content: system },
      { role: "user", content: user }
    ],
    response_format: {
      type: "json_schema",
      json_schema: {
        name: "greenscape_proposal",
        strict: true,
        schema: generatedSchema
      }
    }
  };
  let raw;
  const openRouterApiKey = process.env.OPENROUTER_API_KEY || process.env.OPENAI_API_KEY;
  if (!process.env.BUILT_IN_FORGE_API_URL && openRouterApiKey) {
    const baseUrl = (process.env.OPENROUTER_BASE_URL || "https://openrouter.ai/api/v1").replace(/\/$/, "");
    const response = await fetch(`${baseUrl}/chat/completions`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${openRouterApiKey}`,
        "Content-Type": "application/json",
        "HTTP-Referer": process.env.APP_URL || "http://localhost:3000",
        "X-Title": "Greenscape QuoteFlow"
      },
      body: JSON.stringify({
        ...request,
        reasoning: { effort: "minimal" }
      }),
      signal: AbortSignal.timeout(12e4)
    });
    if (!response.ok)
      throw new Error(
        `OpenRouter request failed (${response.status}): ${await response.text()}`
      );
    raw = await response.json();
  } else {
    raw = await invokeLLM({ ...request, reasoning: { effort: "minimal" } });
  }
  const content = raw.choices?.[0]?.message?.content;
  if (typeof content !== "string")
    throw new Error("The model returned no proposal content");
  const draft = parseGeneratedProposal(content);
  return {
    draft,
    promptTokens: raw.usage?.prompt_tokens ?? null,
    completionTokens: raw.usage?.completion_tokens ?? null
  };
}
function extractJsonString(raw) {
  let cleaned = raw.trim();
  const codeBlockMatch = cleaned.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);
  if (codeBlockMatch) {
    cleaned = codeBlockMatch[1].trim();
  }
  if (!cleaned.startsWith("{") || !cleaned.endsWith("}")) {
    const firstBrace = cleaned.indexOf("{");
    const lastBrace = cleaned.lastIndexOf("}");
    if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
      cleaned = cleaned.slice(firstBrace, lastBrace + 1);
    }
  }
  return cleaned;
}
function normalizeModelPayload(rawJson) {
  if (!rawJson || typeof rawJson !== "object") {
    return rawJson;
  }
  let obj = { ...rawJson };
  if (obj.proposal && typeof obj.proposal === "object" && !Array.isArray(obj.proposal)) {
    obj = { ...obj.proposal, ...obj };
  } else if (obj.data && typeof obj.data === "object" && !Array.isArray(obj.data)) {
    obj = { ...obj.data, ...obj };
  }
  if (!obj.projectSummary && typeof obj.proposal === "string") {
    obj.projectSummary = obj.proposal;
  }
  const rawLineItems = obj.lineItems ?? obj.line_items ?? obj.items ?? obj.scope_items ?? [];
  const lineItems = Array.isArray(rawLineItems) ? rawLineItems : [];
  const normalizedLineItems = lineItems.map((item, idx) => {
    if (!item || typeof item !== "object") {
      return {
        category: "General",
        description: String(item || `Scope item ${idx + 1}`),
        quantity: 1,
        unit: "ea",
        unitPriceCents: 1e4,
        sourceNote: "Site notes"
      };
    }
    const rawCategory = item.category ?? item.type ?? "Landscape";
    const rawDescription = item.description ?? item.item ?? item.name ?? `Scope item ${idx + 1}`;
    const rawUnit = item.unit ?? item.unit_of_measure ?? "sq ft";
    const rawQuantity = Number(item.quantity ?? item.qty ?? item.count ?? 1);
    const quantity = Number.isFinite(rawQuantity) && rawQuantity > 0 ? rawQuantity : 1;
    let unitPriceCents = 1e4;
    if (item.unitPriceCents != null && Number.isFinite(Number(item.unitPriceCents))) {
      unitPriceCents = Math.round(Number(item.unitPriceCents));
    } else if (item.unit_price_cents != null && Number.isFinite(Number(item.unit_price_cents))) {
      unitPriceCents = Math.round(Number(item.unit_price_cents));
    } else if (item.unitPrice != null && Number.isFinite(Number(item.unitPrice))) {
      unitPriceCents = Math.round(Number(item.unitPrice) * 100);
    } else if (item.unit_price != null && Number.isFinite(Number(item.unit_price))) {
      unitPriceCents = Math.round(Number(item.unit_price) * 100);
    } else if (item.price != null && Number.isFinite(Number(item.price))) {
      unitPriceCents = Math.round(Number(item.price) * 100);
    }
    const sourceNote = String(
      item.sourceNote ?? item.source_note ?? item.note ?? "Site walk scope note"
    ).trim() || "Site walk scope note";
    return {
      category: String(rawCategory).trim() || "General",
      description: String(rawDescription).trim() || `Scope item ${idx + 1}`,
      quantity,
      unit: String(rawUnit).trim() || "ea",
      unitPriceCents: Math.max(0, unitPriceCents),
      sourceNote
    };
  });
  if (normalizedLineItems.length === 0) {
    normalizedLineItems.push({
      category: "Mobilization",
      description: "Project mobilization and site layout",
      quantity: 1,
      unit: "project",
      unitPriceCents: 2e5,
      sourceNote: "Initial site walk mobilization"
    });
  }
  const rawRiskFlags = obj.riskFlags ?? obj.risk_flags ?? obj.risks ?? [];
  const normalizedRiskFlags = (Array.isArray(rawRiskFlags) ? rawRiskFlags : []).map((flag) => {
    if (typeof flag === "string") {
      return { severity: "medium", message: flag.trim() };
    }
    if (flag && typeof flag === "object") {
      const sev = String(flag.severity || "medium").toLowerCase();
      const severity = sev === "high" || sev === "low" ? sev : "medium";
      const message = String(
        flag.message || flag.description || flag.note || "General risk flag"
      ).trim();
      return { severity, message: message || "General risk flag" };
    }
    return null;
  }).filter(Boolean);
  const rawAssumptions = obj.assumptions ?? [];
  const assumptions = (Array.isArray(rawAssumptions) ? rawAssumptions : []).map(String);
  const rawExclusions = obj.exclusions ?? [];
  const exclusions = (Array.isArray(rawExclusions) ? rawExclusions : []).map(String);
  const rawQuestions = obj.unansweredQuestions ?? obj.unanswered_questions ?? obj.openQuestions ?? obj.open_questions ?? [];
  const unansweredQuestions = (Array.isArray(rawQuestions) ? rawQuestions : []).map(String);
  const projectSummary = obj.projectSummary ?? obj.project_summary ?? obj.summary ?? "";
  const customerMessage = obj.customerMessage ?? obj.customer_message ?? obj.coverNote ?? obj.cover_note ?? "";
  return {
    projectSummary,
    lineItems: normalizedLineItems,
    assumptions,
    exclusions,
    unansweredQuestions,
    riskFlags: normalizedRiskFlags,
    customerMessage
  };
}
function parseGeneratedProposal(rawContent) {
  let json;
  if (typeof rawContent === "string") {
    const cleaned = extractJsonString(rawContent);
    try {
      json = JSON.parse(cleaned);
    } catch (err) {
      throw new Error(
        `Failed to parse model JSON: ${err instanceof Error ? err.message : String(err)}`
      );
    }
  } else {
    json = rawContent;
  }
  const normalized = normalizeModelPayload(json);
  const parsed = generatedProposalSchema.safeParse(normalized);
  if (!parsed.success) {
    throw new Error(
      `The model response failed validation: ${parsed.error.message}`
    );
  }
  return parsed.data;
}
async function generateAndPersistProposal(rawInput) {
  const input = proposalInputSchema.parse(rawInput);
  const { draft, promptTokens, completionTokens } = await requestStructuredProposal(input);
  const riskFlags = evaluateGuardrails(
    draft.lineItems,
    draft.unansweredQuestions,
    draft.riskFlags
  );
  const row = await createProposalRow({
    ...input,
    customerEmail: input.customerEmail || null,
    customerPhone: input.customerPhone || null,
    desiredStartDate: input.desiredStartDate || null,
    budgetRange: input.budgetRange || null,
    projectSummary: draft.projectSummary,
    lineItemsJson: JSON.stringify(draft.lineItems),
    assumptionsJson: JSON.stringify(draft.assumptions),
    exclusionsJson: JSON.stringify(draft.exclusions),
    unansweredQuestionsJson: JSON.stringify(draft.unansweredQuestions),
    riskFlagsJson: JSON.stringify(riskFlags),
    customerMessage: draft.customerMessage,
    totalCents: calculateTotal(draft.lineItems),
    aiModel: getProposalModel(),
    promptTokens,
    completionTokens
  });
  if (!row) throw new Error("Proposal was generated but could not be loaded");
  return hydrateProposal(row);
}
async function persistEdits(id, rawEdits) {
  const edits = editableSchema.parse(rawEdits);
  const current = await getProposalRow(id);
  if (!current)
    throw new TRPCError3({ code: "NOT_FOUND", message: "Proposal not found" });
  if (current.status === "approved")
    throw new TRPCError3({
      code: "BAD_REQUEST",
      message: "Approved proposals are immutable; create a new version instead."
    });
  const reviewerFlags = edits.riskFlags.filter(
    (flag) => !flag.message.includes("open question") && !flag.message.includes("typical $8,000 project floor") && !flag.message.includes("historical $120,000 project range")
  );
  const riskFlags = evaluateGuardrails(
    edits.lineItems,
    edits.unansweredQuestions,
    reviewerFlags
  );
  const row = await updateProposalRow(id, {
    projectSummary: edits.projectSummary,
    lineItemsJson: JSON.stringify(edits.lineItems),
    assumptionsJson: JSON.stringify(edits.assumptions),
    exclusionsJson: JSON.stringify(edits.exclusions),
    unansweredQuestionsJson: JSON.stringify(edits.unansweredQuestions),
    riskFlagsJson: JSON.stringify(riskFlags),
    customerMessage: edits.customerMessage,
    totalCents: calculateTotal(edits.lineItems),
    version: current.version + 1
  });
  if (!row) throw new Error("Updated proposal could not be loaded");
  return hydrateProposal(row);
}
function webhookPayload(proposal) {
  return {
    event: "proposal.approved",
    occurredAt: (/* @__PURE__ */ new Date()).toISOString(),
    source: "greenscape-quoteflow",
    proposal: {
      id: proposal.id,
      customerName: proposal.customerName,
      customerEmail: proposal.customerEmail,
      customerPhone: proposal.customerPhone,
      projectAddress: proposal.projectAddress,
      projectType: proposal.projectType,
      totalCents: proposal.totalCents,
      summary: proposal.projectSummary,
      lineItems: proposal.lineItems,
      customerMessage: proposal.customerMessage,
      version: proposal.version
    }
  };
}
async function deliverWebhook(proposal) {
  const endpoint = process.env.OUTBOUND_WEBHOOK_URL || DEMO_WEBHOOK_URL;
  const isDemo = endpoint.includes("ntfy.sh/");
  const response = await fetch(endpoint, {
    method: "POST",
    headers: isDemo ? {
      "Content-Type": "text/plain",
      Title: `QuoteFlow approved: ${proposal.customerName}`
    } : {
      "Content-Type": "application/json",
      "X-QuoteFlow-Event": "proposal.approved"
    },
    body: isDemo ? `Proposal #${proposal.id} approved for ${proposal.customerName}: $${(proposal.totalCents / 100).toLocaleString("en-US", { minimumFractionDigits: 2 })}. Assessment demo; customer contact details are intentionally omitted.` : JSON.stringify(webhookPayload(proposal)),
    signal: AbortSignal.timeout(15e3)
  });
  const responseText = (await response.text()).slice(0, 500);
  await createIntegrationEvent({
    proposalId: proposal.id,
    destination: isDemo ? "ntfy assessment notifier" : new URL(endpoint).host,
    status: response.ok ? "sent" : "failed",
    httpStatus: response.status,
    responseSnippet: responseText
  });
  if (!response.ok) throw new Error(`Webhook returned ${response.status}`);
  return {
    destination: isDemo ? "assessment notifier" : new URL(endpoint).host,
    status: response.status
  };
}
async function approveAndDeliver(id) {
  const currentRow = await getProposalRow(id);
  if (!currentRow)
    throw new TRPCError3({ code: "NOT_FOUND", message: "Proposal not found" });
  const current = hydrateProposal(currentRow);
  if (current.status === "approved")
    throw new TRPCError3({
      code: "BAD_REQUEST",
      message: "Proposal is already approved"
    });
  const blockers = current.riskFlags.filter((flag) => flag.severity === "high");
  if (blockers.length)
    throw new TRPCError3({
      code: "PRECONDITION_FAILED",
      message: `Resolve ${blockers.length} high-severity guardrail before approval.`
    });
  const approvedRow = await updateProposalRow(id, {
    status: "approved",
    approvedAt: /* @__PURE__ */ new Date()
  });
  if (!approvedRow) throw new Error("Approved proposal could not be loaded");
  const approved = hydrateProposal(approvedRow);
  try {
    const delivery = await deliverWebhook(approved);
    return { proposal: approved, delivery };
  } catch (error) {
    if (!(error instanceof Error && error.message.startsWith("Webhook returned"))) {
      await createIntegrationEvent({
        proposalId: id,
        destination: "configured webhook",
        status: "failed",
        responseSnippet: error instanceof Error ? error.message.slice(0, 500) : "Unknown delivery error"
      });
    }
    throw new TRPCError3({
      code: "BAD_GATEWAY",
      message: "Proposal approved, but external delivery failed. The attempt was logged for retry."
    });
  }
}

// server/routers.ts
var lineItemInput = z3.object({
  category: z3.string(),
  description: z3.string(),
  quantity: z3.number(),
  unit: z3.string(),
  unitPriceCents: z3.number().int(),
  sourceNote: z3.string()
});
var appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query((opts) => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => {
      ctx.res.clearCookie(COOKIE_NAME, {
        ...getSessionCookieOptions(ctx.req),
        maxAge: -1
      });
      return { success: true };
    })
  }),
  proposal: router({
    list: publicProcedure.query(async () => {
      const proposals2 = (await listProposalRows()).map(hydrateProposal);
      const metrics = {
        totalProposals: proposals2.length,
        awaitingApproval: proposals2.filter((item) => item.status === "draft").length,
        approved: proposals2.filter((item) => item.status === "approved").length,
        pipelineValueCents: proposals2.reduce(
          (sum, item) => sum + item.totalCents,
          0
        )
      };
      return { proposals: proposals2, metrics };
    }),
    generate: publicProcedure.input(proposalInputSchema).mutation(({ input }) => generateAndPersistProposal(input)),
    update: publicProcedure.input(
      z3.object({
        id: z3.number().int().positive(),
        projectSummary: z3.string(),
        lineItems: z3.array(lineItemInput),
        assumptions: z3.array(z3.string()),
        exclusions: z3.array(z3.string()),
        unansweredQuestions: z3.array(z3.string()),
        riskFlags: z3.array(
          z3.object({
            severity: z3.enum(["low", "medium", "high"]),
            message: z3.string()
          })
        ),
        customerMessage: z3.string()
      })
    ).mutation(({ input }) => {
      const { id, ...edits } = input;
      return persistEdits(id, edits);
    }),
    approve: publicProcedure.input(z3.object({ id: z3.number().int().positive() })).mutation(({ input }) => approveAndDeliver(input.id)),
    integrationEvents: publicProcedure.input(z3.object({ proposalId: z3.number().int().positive() })).query(({ input }) => listIntegrationEvents(input.proposalId))
  })
});

// server/_core/context.ts
async function createContext(opts) {
  return {
    req: opts.req,
    res: opts.res,
    user: null
  };
}

// server/_core/app.ts
function createExpressApp() {
  const app2 = express();
  app2.use(express.json({ limit: "50mb" }));
  app2.use(express.urlencoded({ limit: "50mb", extended: true }));
  registerStorageProxy(app2);
  app2.use(
    "/api/trpc",
    createExpressMiddleware({
      router: appRouter,
      createContext
    })
  );
  return app2;
}

// server/_core/api-entry.ts
var app = createExpressApp();
var api_entry_default = app;
export {
  api_entry_default as default
};
